[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
   let g:NERDTreeShowHidden = 1
   map <C-n> <plug>NERDTreeTabsToggle<CR>
   "au MyAutoCmd VimEnter * execute 'NERDTreeTabsToggle'
'''

#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
   if argc() == 0
      let g:nerdtree_tabs_open_on_console_startup = 1
   end
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell'


[[plugins]]
repo = 'tyru/open-browser.vim'


[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'
