#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'


#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#depends = ['neosnippet-snippets']
#on_i = 1
#on_ft = ['snippet']
#
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_refresh_always = 1
'''
# hook_source = '''
#   let g:deoplete#enable_at_startup = 1
#   let g:deoplete#auto_complete_delay = 0
#   let g:deoplete#auto_complete_start_length = 1
#   let g:deoplete#enable_camel_case = 0
#   let g:deoplete#enable_ignore_case = 0
#   let g:deoplete#enable_refresh_always = 0
#   let g:deoplete#enable_smart_case = 1
#   let g:deoplete#file#enable_buffer_path = 1
#   let g:deoplete#max_list = 10000
#   inoremap <expr><tab> pumvisible() ? "\<C-n>" :
#         \ neosnippet#expandable_or_jumpable() ?
#         \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
# '''
on_i = 1

# [[plugins]]
# repo = 'zchee/deoplete-jedi'
# on_ft = 'python'
# hook_add = '''
#     let g:deoplete#sources#jedi#python_path = '/home/naoki/.pyenv/shims/python' 
# '''


[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1


[[plugins]]
repo = 'ervandew/supertab'


[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']


[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
   let g:quickrun_config = {}
   let g:quickrun_config['tex'] = {
   \ 'command' : 'latexmk',
   \ 'outputter' : 'error',
   \ 'outputter/error/success' : 'null',
   \ 'outputter/error/error' : 'quickfix',
   \ 'srcfile' : expand("%"),
   \ 'cmdopt': '-pdfdvi -pv',
   \ 'hook/sweep/files' : [
   \                      '%S:p:r.aux',
   \                      '%S:p:r.bbl',
   \                      '%S:p:r.blg',
   \                      '%S:p:r.dvi',
   \                      '%S:p:r.fdb_latexmk',
   \                      '%S:p:r.fls',
   \                      '%S:p:r.log',
   \                      '%S:p:r.out'
   \                      ],
   \ 'exec': '%c %o %s',
   \}

   let g:quickrun_config.tmptex = {
   \   'exec': [
   \           'mv %s %a/tmptex.latex',
   \           'latexmk -pdfdvi -pv -output-directory=%a %a/tmptex.latex',
   \           ],
   \   'args' : expand("%:p:h:gs?\\\\?/?"),
   \   'outputter' : 'error',
   \   'outputter/error/error' : 'quickfix',
   \
   \   'hook/eval/enable' : 1,
   \   'hook/eval/cd' : "%s:r",
   \
   \   'hook/eval/template' : '\documentclass{jsarticle}'
   \                         .'\usepackage[dvipdfmx]{graphicx, hyperref}'
   \                         .'\usepackage{float}'
   \                         .'\usepackage{amsmath,amssymb,amsthm,ascmac,mathrsfs}'
   \                         .'\allowdisplaybreaks[1]'
   \                         .'\theoremstyle{definition}'
   \                         .'\newtheorem{theorem}{定理}'
   \                         .'\newtheorem*{theorem*}{定理}'
   \                         .'\newtheorem{definition}[theorem]{定義}'
   \                         .'\newtheorem*{definition*}{定義}'
   \                         .'\renewcommand\vector[1]{\mbox{\boldmath{\$#1\$}}}'
   \                         .'\DeclareMathOperator{\divergence}{div}'
   \                         .'\DeclareMathOperator{\grad}{grad}'
   \                         .'\DeclareMathOperator{\rot}{rot}'
   \                         .'\begin{document}'
   \                         .'%s'
   \                         .'\end{document}',
   \
   \   'hook/sweep/files' : [
   \                        '%a/tmptex.latex',
   \                        '%a/tmptex.out',
   \                        '%a/tmptex.fdb_latexmk',
   \                        '%a/tmptex.log',
   \                        '%a/tmptex.aux',
   \                        '%a/tmptex.dvi'
   \                        ],
   \}

'''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_source = '''
   let g:previm_disable_default_css = 1
   let g:previm_custom_css_path = '~/.vim/templates/previm/markdown.css'
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']


[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']


[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['cpp']
# hook_source = '''
#     let g:clang_c_options = '-std=c11'
#     let g:clang_cpp_options = '-std=c++1z -stdlib=libc++ –pedantic-errors'
#     let g:clang_format_auto = 1
#     let g:clang_format_style = 'Google'
#     let g:clang_check_syntax_auto = 1
# '''

