#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'


#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#depends = ['neosnippet-snippets']
#on_i = 1
#on_ft = ['snippet']
#
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'


#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#on_event = 'InsertCharPre'
#hook_source = '''
#  let g:deoplete#enable_at_startup = 1
#  let g:deoplete#auto_complete_delay = 0
#  let g:deoplete#auto_complete_start_length = 1
#  let g:deoplete#enable_camel_case = 0
#  let g:deoplete#enable_ignore_case = 0
#  let g:deoplete#enable_refresh_always = 0
#  let g:deoplete#enable_smart_case = 1
#  let g:deoplete#file#enable_buffer_path = 1
#  let g:deoplete#max_list = 10000
#  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
#        \ neosnippet#expandable_or_jumpable() ?
#        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
#'''
#on_i = 1

#[[plugins]]
#repo = 'zchee/deoplete-jedi'
#on_ft = 'python'
#hook_add = '''
#    let g:deoplete#sources#jedi#python_path = '/home/naoki/.pyenv/shims/python' 
#'''


[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1


[[plugins]]
repo = 'ervandew/supertab'

